{
 "title": "Anomalizer Logs 1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "logger" },
   { "name": "severity", "query": "info, error" },
   { "name": "level", "query": "INFO, ERROR" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "load test client times per thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(load_test_client_request_time_per_thread_sum[1m])/rate(load_test_client_request_time_per_thread_count[1m])"
    }
   ]
  },
  {
   "title": "metrics from logs / request times by thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(avg_over_time({application=\"anomalizer\", logger=\"anomalizer-metrics\", severity=\"info\"} |~ \"client_request_time_per_thread\\\"\" | json | unwrap value[1m]))",
     "legendFormat": "{{metric}}: {{endpoint}}  {{thread}}"
    }
   ]
  },
  {
   "title": "Logs (from loki)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count_over_time({application=\"anomalizer\", logger=~\".*$logger.*\", severity=~\"$severity\"}[1m])  ",
     "legendFormat": "{{logger}} {{severity}}"
    }
   ]
  },
  {
   "title": "Logs (from prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(anomalizer_logs_total{level=\"${level}\"}[1m])*60",
     "legendFormat": "{{name}} {{level}}"
    }
   ]
  },
  {
   "title": "Anomalizer",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<iframe src=\"http://localhost:8056\" width=\"2000\" height=\"500\"/>\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}