{
 "title": "Anomalizer Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "logger",
    "query": {}
   },
   { "name": "severity", "query": "info, error" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "metrics as logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "load test client times per thread",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(load_test_client_request_time_per_thread_sum[1m])/rate(load_test_client_request_time_per_thread_count[1m])"
      }
     ]
    },
    {
     "title": "metrics from logs / request times by thread",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "(avg_over_time({application=\"anomalizer\", logger=\"anomalizer-metrics\", severity=\"info\"} |~ \"client_request_time_per_thread\\\"\" | json | unwrap value[1m]))",
       "legendFormat": "{{metric}}: {{endpoint}}  {{thread}}"
      }
     ]
    }
   ]
  },
  { "title": "log metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs (from prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "rate(anomalizer_logs_total{level=~\"${severity}\", job!=\"anomalizer\", name=~\"${logger}\"}[1m])*60",
     "legendFormat": "{{name}} {{level}}"
    }
   ]
  },
  {
   "title": "Logs (from loki)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "count_over_time({application=\"anomalizer\", logger=~\".*$logger.*\", severity=~\"$severity\"}[1m])  ",
     "legendFormat": "{{logger}} {{severity}}"
    }
   ]
  },
  {
   "title": "log lines",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{application=\"anomalizer\", logger=~\".*$logger.*\", severity=~\"$severity\"} |= ``"
    }
   ]
  },
  {
   "title": "anomalizer iframe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anomalizer",
     "type": "text",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "<iframe src=\"http://localhost:8056\" width=\"2000\" height=\"1000\"/>\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}