version: "2"
services:

  # anomalizer
  anomalizer-api:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    ports:
      - "8056:8056"
    environment:
      - X-LOKI=http://host.docker.internal:3100
      - ANOMALIZER_ENGINE=http://anomalizer-engine:8060
      - ANOMALIZER_IMAGES=http://anomalizer-images-{SHARD}:8061
      - ANOMALIZER_CORRELATOR=http://anomalizer-correlator:8062
    entrypoint:
      python anomalizer-api.py
    depends_on:
      - anomalizer-engine
      - anomalizer-images-0
      - anomalizer-images-1
      - anomalizer-images-2
      - anomalizer-correlator
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-images-0:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    environment:
      - I_SHARD=0
      - X-LOKI=http://host.docker.internal:3100
      - ANOMALIZER_IMAGES_PORT=8061
      - ANOMALIZER_ENGINE=http://anomalizer-engine:8060
      - ANOMALIZER_API=http://anomalizer-api:8056
      - ANOMALIZER_CORRELATOR=http://anomalizer-correlator:8062
    entrypoint:
      python anomalizer-images.py
    depends_on:
      - anomalizer-engine
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-images-1:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    environment:
      - I_SHARD=1
      - X-LOKI=http://host.docker.internal:3100
      - ANOMALIZER_IMAGES_PORT=8061
      - ANOMALIZER_ENGINE=http://anomalizer-engine:8060
      - ANOMALIZER_API=http://anomalizer-api:8056
      - ANOMALIZER_CORRELATOR=http://anomalizer-correlator:8062
    entrypoint:
      python anomalizer-images.py
    depends_on:
      - anomalizer-engine
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-images-2:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    environment:
      - I_SHARD=2
      - X-LOKI=http://host.docker.internal:3100
      - ANOMALIZER_IMAGES_PORT=8061
      - ANOMALIZER_ENGINE=http://anomalizer-engine:8060
      - ANOMALIZER_API=http://anomalizer-api:8056
      - ANOMALIZER_CORRELATOR=http://anomalizer-correlator:8062
    entrypoint:
      python anomalizer-images.py
    depends_on:
      - anomalizer-engine
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-correlator:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    environment:
      - X-LOKI=http://host.docker.internal:3100
      - ANOMALIZER_API=http://anomalizer-api:8056
    entrypoint:
      python anomalizer-correlator.py
    depends_on:
      - anomalizer-engine
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-engine:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    entrypoint:
      python anomalizer-engine.py
    environment:
      - PROMETHEUS=http://mini-prom:19090 # change this port to point to another prometheus.
      - X-LOKI=http://host.docker.internal:3100
    ports:
      - "8060:8060"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  mini-prom:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    ports:
      - "19090:19090"
    entrypoint:
      python mini-prom.py
    environment:
      - X-LOKI=http://host.docker.internal:3100
    volumes:
      - ../python/microservices/mini-prom.yaml:/microservices/mini-prom.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  anomalizer-load-test:
    image: ghcr.io/pogadog/anomalizer-multi:latest
    ports:
      - "7070:7070"
    entrypoint:
      python load-test.py
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'


