version: "2"
services:

  # anomalizer
  anomalizer:
    image: ghcr.io/pogadog/anomalizer-arm64:latest
    ports:
      - "8056:8056"
    environment:
      - PROMETHEUS=host.docker.internal:9090 # change this port to point to another prometheus.
      - LOKI=http://host.docker.internal:3100
    #depends_on:
      - anomalizer-prometheus
      #- mini-prom

  # anomalizer-ui
  anomalizer-ui:
    image: ghcr.io/pogadog/anomalizer-ui-arm64:latest
    environment:
      # ENDPOINT is relative to *browser*
      - ENDPOINT=localhost:8056
      - PORT=3001
    ports:
      - "3001:3001"

  anomalizer-load-test:
    image: ghcr.io/pogadog/anomalizer-load-test-arm64:latest
    ports:
      - "7070:7070"

  anomalizer-prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus-data:/prometheus
    ports:
      - "9090:9090" # expose this prometheus on 9091 host port


