FROM python:3.9.12

COPY python/requirements.txt .
RUN pip install -r requirements.txt

ENV PROMETHEUS "host.docker.internal:9090"
COPY python/microservices/ ./microservices/
COPY docker/web-build/ ./microservices/web-build/

USER 1000

LABEL org.opencontainers.image.source https://github.com/pogadog/anomalizer

WORKDIR microservices
ENTRYPOINT ["python", "-u", "anomalizer-service.py"]
