version: "3"
services:
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./otel-tempo-wavefront.yaml:/conf/collector-config.yaml
    ports:
      - "4317:4317"

