version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
      - ../prometheus-data:/prometheus
    ports:
      - "9090:9090" # expose this prometheus on 9091 host port

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - .:/mnt/config
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      # persist the grafana store -- stop losing dashbaords.
      - ../grafana-storage:/var/lib/grafana
    environment:
      # allow embedding.
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PLUGINS_ENABLE_ALPHA=true

  # add in telegraf, influxdb and opentsdb just to see what we can do
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
    ports:
      - 4242:4242
      - 60030:60030
    networks:
      - monitoring
    volumes:
      - "./data:/data/hbase"

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/vol01/Docker/monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=pogadog
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    networks:
      - monitoring
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

volumes:
  influxdb-volume:

networks:
  monitoring: