version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
      - ../prometheus-data:/prometheus
    ports:
      - "9090:9090" # expose this prometheus on 9091 host port

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - .:/mnt/config
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
