apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: anomalizer-images
  name: anomalizer-images
spec:
  ports:
    - name: "8061"
      port: 8061
      targetPort: 8061
  selector:
    io.kompose.service: anomalizer-images
status:
  loadBalancer: {}
