apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: anomalizer-load-test
  name: anomalizer-load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anomalizer-load-test
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: anomalizer-load-test
    spec:
      imagePullSecrets:
        - name: anomalizer-secret
      containers:
        - command:
            - python
            - load-test.py
          image: ghcr.io/pogadog/anomalizer-multi:latest
          name: anomalizer-load-test
          ports:
            - containerPort: 7070
          resources: {}
      restartPolicy: Always
status: {}
