apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: anomalizer-api
  name: anomalizer-api
spec:
  ports:
    - name: "8056"
      port: 8056
      targetPort: 8056
  selector:
    io.kompose.service: anomalizer-api
status:
  loadBalancer: {}
