apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mini-prom
  name: mini-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mini-prom
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../anomalizer-compose-microservices.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mini-prom
    spec:
      imagePullSecrets:
        - name: anomalizer-secret
      containers:
        - command:
            - python
            - mini-prom.py
          env:
            - name: X-LOKI
              value: http://host.docker.internal:3100
          image: ghcr.io/pogadog/anomalizer-multi:latest
          name: mini-prom
          ports:
            - containerPort: 9090
          resources: {}
      restartPolicy: Always
status: {}
